# -*- coding: utf-8 -*-
{
    "name": "Idea box",
    "version": "saas~17.1.1.0",
    "category": "Employees",
    "author": "Hodei",
    "depends": ["base", "mail"],
    "data": [
        "data/ir_model.xml",
        "data/ir_model_fields.xml",
        "data/ir_ui_view.xml",
        "data/ir_actions_act_window.xml",
        "data/ir_ui_menu.xml",
        "data/ir_model_access.xml",
        "data/ir_default.xml",
    ],
    "application": False,
    "license": "OPL-1",
    "images": ["static/description/banner.png"],
    "sequence": 10,
    "live_test_url": "https://www.hodei.net",
    "summary": 'Captures, organizes, and prioritizes employee suggestions.',
    "support": "https://www.hodei.net",
    "website": "https://www.hodei.net",
}
