# -*- coding: utf-8 -*-
{
    "name": "Idea box",
    "version": "17.0.0.1",
    "category": "Employees",
    "author": "Hodei",
    "depends": ["base"],
    "data": [
        "data/ir_model.xml",
        "data/ir_model_fields.xml",
        "data/ir_ui_view.xml",
        "data/ir_actions_act_window.xml",
        "data/ir_ui_menu.xml",
        "data/ir_model_access.xml",
        "data/ir_default.xml",
    ],
    "application": False,
    "license": "OPL-1",
    "icon": "static/description/icon.png",
    "images": ["static/description/banner.png"],
    "sequence": 10,
    "live_test_url": "https://www.hodei.net",
    "summary": 'The "Idea Box" module for Odoo version 17 is a versatile tool designed to capture and organize employee suggestions for improving company operations and workplace environment. This module provides a Kanban view for easy visualization and management of ideas. Within the form view, users can define each idea with fields for the name, person responsible, tags, description, importance, and priority. This employee-driven innovation tool fosters a collaborative culture, streamlines the idea management process, and prioritizes initiatives for effective implementation.',
    "support": "https://www.hodei.net",
    "website": "https://www.hodei.net",
}
